import API from './axios.js'

export const createPost = (data) => API.post('/posts', data)
export const getFeedPosts = () => API.get('/posts/feed')
export const getPost = (id) => API.get(`/posts/${id}`)
export const updatePost = (id, data) => API.put(`/posts/${id}`, data)
export const deletePost = (id) => API.delete(`/posts/${id}`)
export const reactToPost = (id, type) => API.post(`/posts/${id}/react`, { type })
export const getPostsByUser = (userId) => API.get(`/posts/user/${userId}`)
export const addComment = (id, content) => API.post(`/posts/${id}/comments`, { content })
export const getComments = (id) => API.get(`/posts/${id}/comments`)
export const addReply = (commentId, content) => API.post(`/posts/comments/${commentId}/replies`, { content })
export const getReplies = (commentId) => API.get(`/posts/comments/${commentId}/replies`)
export const attemptPost = (id) => API.post(`/posts/${id}/attempt`)
export const getAttempted = (id) => API.get(`/posts/${id}/attempted`)
export const bookmarkPost = (id) => API.post(`/posts/${id}/bookmark`)
export const getBookmarks = () => API.get('/posts/bookmarks')
export const repostPost = (id) => API.post(`/posts/${id}/repost`)
export const getPostsByHashtag = (tag) => API.get(`/posts/hashtag/${tag}`)